version: '3.8'
services:
  backend:
    build: ./backend
    command: flask run --host=0.0.0.0 --port=5000 --reload
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    ports:
      - '5000:5000'
    depends_on:
      - db
      - redis
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:7
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
volumes:
  postgres_data:
  redis_data: 